import type { LanguageCode } from './locales';

const en = {
  overview: 'Overview', generator: 'Generator', production: 'Production', eqMaster: 'EQ / Master', publishing: 'Publishing', marketplace: 'Marketplace', discovery: 'Discovery', analytics: 'Analytics', assistant: 'AI Assistant', cloud: 'Sonara Cloud', collaboration: 'Collaboration', enterprise: 'Enterprise', settings: 'Settings',
  engine: 'Engine', online: 'Online', refresh: 'Refresh', status: 'Status', musicStudio: 'Music Studio', ready: 'Ready',
  generateMusic: 'Generate Music', prompt: 'Prompt', genreFamily: 'Genre family', genre: 'Genre', subgenre: 'Subgenre', mood: 'Mood', key: 'Key', duration: 'Duration', title: 'Title', bpm: 'BPM', lyrics: 'Lyrics / Vocal mode', generate: 'Generate Track', generating: 'ACE-Step is generating...', audioReady: 'Audio ready', download: 'Download', play: 'Play', pause: 'Pause',
  language: 'Language', languageHelp: 'Choose the interface language. The selection is saved on this device.', appearance: 'Appearance', account: 'Account', logout: 'Sign out', defaultDuration: 'Default duration', system: 'System',
  overviewTitle: 'Sonara Command Center', overviewSubtitle: 'Music creation, production, distribution and intelligence in one workspace.',
  productionTitle: 'Production Center', productionSubtitle: 'Mixing, mastering, stems and export workflow.', publishingTitle: 'Publishing Studio', publishingSubtitle: 'Prepare releases, metadata and distribution.', marketplaceTitle: 'Marketplace', marketplaceSubtitle: 'Creator assets, samples, presets and production tools.', discoveryTitle: 'Worldwide Discovery', discoverySubtitle: 'Explore scenes, genres and creators around the world.', analyticsTitle: 'Analytics', analyticsSubtitle: 'Performance, audience and release intelligence.', assistantTitle: 'AI Assistant', assistantSubtitle: 'Creative support powered by Sonara.', cloudTitle: 'Sonara Cloud', cloudSubtitle: 'Projects, sessions and synchronized assets.', collaborationTitle: 'Collaboration', collaborationSubtitle: 'Work with artists, producers and teams.', enterpriseTitle: 'Enterprise Center', enterpriseSubtitle: 'Administration, security and professional workflows.', settingsTitle: 'Settings', settingsSubtitle: 'Language, account and Sonara preferences.',
  welcome: 'Welcome to Sonara', signInSubtitle: 'Access the Sonara Enterprise creative ecosystem.', email: 'Email', password: 'Password', signIn: 'Sign in', createAccount: 'Create account', register: 'Register', forgotPassword: 'Forgot password?', resetPassword: 'Send password reset', continueGoogle: 'Continue with Google', or: 'or', guest: 'Continue as guest', backToLogin: 'Back to sign in', bootInitializing: 'INITIALIZING CREATIVE INTELLIGENCE', bootEngine: 'ACE-Step 1.5 · Modal NVIDIA L4', authConfigMissing: 'Authentication is temporarily unavailable because the Firebase production credentials are not configured.',
  seconds: 'seconds', minutes: 'minutes', globalCatalog: 'Global music catalog', catalogHelp: 'Worldwide genres and subgenres available for ACE-Step prompting.'
} as const;

type UiDictionary = Partial<Record<keyof typeof en, string>>;

const packs: Partial<Record<LanguageCode, UiDictionary>> = {
  it: {
    overview:'Panoramica', generator:'Generatore', production:'Produzione', eqMaster:'EQ / Master', publishing:'Pubblicazione', marketplace:'Marketplace', discovery:'Scoperta', analytics:'Analisi', assistant:'Assistente AI', cloud:'Sonara Cloud', collaboration:'Collaborazione', enterprise:'Enterprise', settings:'Impostazioni', engine:'Motore', online:'Online', refresh:'Aggiorna', status:'Stato', musicStudio:'Studio Musicale', ready:'Pronto',
    generateMusic:'Genera Musica', prompt:'Prompt', genreFamily:'Famiglia musicale', genre:'Genere', subgenre:'Sottogenere', mood:'Atmosfera', key:'Tonalità', duration:'Durata', title:'Titolo', bpm:'BPM', lyrics:'Testo / Modalità vocale', generate:'Genera Brano', generating:'ACE-Step sta generando...', audioReady:'Audio pronto', download:'Scarica', play:'Riproduci', pause:'Pausa', language:'Lingua', languageHelp:'Scegli la lingua dell’interfaccia. La selezione viene salvata su questo dispositivo.', appearance:'Aspetto', account:'Account', logout:'Esci', defaultDuration:'Durata predefinita', system:'Sistema',
    overviewTitle:'Centro di Comando Sonara', overviewSubtitle:'Creazione, produzione, distribuzione e intelligenza musicale in un unico ambiente.', productionTitle:'Centro Produzione', productionSubtitle:'Mixing, mastering, stem ed esportazione.', publishingTitle:'Studio Pubblicazione', publishingSubtitle:'Prepara release, metadati e distribuzione.', marketplaceTitle:'Marketplace', marketplaceSubtitle:'Asset, sample, preset e strumenti per creator.', discoveryTitle:'Scoperta Mondiale', discoverySubtitle:'Esplora scene, generi e creator di tutto il mondo.', analyticsTitle:'Analisi', analyticsSubtitle:'Prestazioni, pubblico e intelligence delle release.', assistantTitle:'Assistente AI', assistantSubtitle:'Supporto creativo integrato in Sonara.', cloudTitle:'Sonara Cloud', cloudSubtitle:'Progetti, sessioni e asset sincronizzati.', collaborationTitle:'Collaborazione', collaborationSubtitle:'Lavora con artisti, producer e team.', enterpriseTitle:'Centro Enterprise', enterpriseSubtitle:'Amministrazione, sicurezza e flussi professionali.', settingsTitle:'Impostazioni', settingsSubtitle:'Lingua, account e preferenze Sonara.',
    welcome:'Benvenuto in Sonara', signInSubtitle:'Accedi all’ecosistema creativo Sonara Enterprise.', email:'Email', password:'Password', signIn:'Accedi', createAccount:'Crea account', register:'Registrati', forgotPassword:'Password dimenticata?', resetPassword:'Invia recupero password', continueGoogle:'Continua con Google', or:'oppure', guest:'Continua come ospite', backToLogin:'Torna all’accesso', bootInitializing:'INIZIALIZZAZIONE INTELLIGENZA CREATIVA', bootEngine:'ACE-Step 1.5 · Modal NVIDIA L4', authConfigMissing:'Autenticazione temporaneamente non disponibile: le credenziali Firebase di produzione non sono configurate.', seconds:'secondi', minutes:'minuti', globalCatalog:'Catalogo musicale mondiale', catalogHelp:'Generi e sottogeneri di tutto il mondo disponibili per i prompt ACE-Step.'
  },
  es: { overview:'Resumen', generator:'Generador', production:'Producción', publishing:'Publicación', discovery:'Descubrir', analytics:'Analíticas', assistant:'Asistente IA', collaboration:'Colaboración', settings:'Configuración', generateMusic:'Generar música', genreFamily:'Familia musical', genre:'Género', subgenre:'Subgénero', mood:'Estado de ánimo', key:'Tonalidad', duration:'Duración', title:'Título', lyrics:'Letra / Modo vocal', generate:'Generar pista', language:'Idioma', account:'Cuenta', logout:'Cerrar sesión', welcome:'Bienvenido a Sonara', signInSubtitle:'Accede al ecosistema creativo Sonara Enterprise.', password:'Contraseña', signIn:'Iniciar sesión', createAccount:'Crear cuenta', register:'Registrarse', forgotPassword:'¿Olvidaste la contraseña?', resetPassword:'Enviar recuperación', continueGoogle:'Continuar con Google', or:'o', guest:'Continuar como invitado', backToLogin:'Volver al acceso', seconds:'segundos', minutes:'minutos' },
  fr: { overview:'Vue d’ensemble', generator:'Générateur', production:'Production', publishing:'Publication', discovery:'Découverte', analytics:'Analytique', assistant:'Assistant IA', collaboration:'Collaboration', settings:'Paramètres', generateMusic:'Générer de la musique', genreFamily:'Famille musicale', genre:'Genre', subgenre:'Sous-genre', mood:'Ambiance', key:'Tonalité', duration:'Durée', title:'Titre', lyrics:'Paroles / Mode vocal', generate:'Générer le morceau', language:'Langue', account:'Compte', logout:'Déconnexion', welcome:'Bienvenue sur Sonara', signInSubtitle:'Accédez à l’écosystème créatif Sonara Enterprise.', password:'Mot de passe', signIn:'Se connecter', createAccount:'Créer un compte', register:'S’inscrire', forgotPassword:'Mot de passe oublié ?', resetPassword:'Envoyer la réinitialisation', continueGoogle:'Continuer avec Google', or:'ou', guest:'Continuer en invité', backToLogin:'Retour à la connexion', seconds:'secondes', minutes:'minutes' },
  de: { overview:'Übersicht', generator:'Generator', production:'Produktion', publishing:'Veröffentlichung', discovery:'Entdecken', analytics:'Analysen', assistant:'KI-Assistent', collaboration:'Zusammenarbeit', settings:'Einstellungen', generateMusic:'Musik generieren', genreFamily:'Musikfamilie', genre:'Genre', subgenre:'Subgenre', mood:'Stimmung', key:'Tonart', duration:'Dauer', title:'Titel', lyrics:'Text / Gesangsmodus', generate:'Track generieren', language:'Sprache', account:'Konto', logout:'Abmelden', welcome:'Willkommen bei Sonara', signInSubtitle:'Zugang zum kreativen Sonara Enterprise Ökosystem.', password:'Passwort', signIn:'Anmelden', createAccount:'Konto erstellen', register:'Registrieren', forgotPassword:'Passwort vergessen?', resetPassword:'Zurücksetzen senden', continueGoogle:'Mit Google fortfahren', or:'oder', guest:'Als Gast fortfahren', backToLogin:'Zurück zur Anmeldung', seconds:'Sekunden', minutes:'Minuten' },
  pt: { overview:'Visão geral', generator:'Gerador', production:'Produção', publishing:'Publicação', discovery:'Descoberta', analytics:'Análises', assistant:'Assistente IA', collaboration:'Colaboração', settings:'Configurações', generateMusic:'Gerar música', genreFamily:'Família musical', genre:'Gênero', subgenre:'Subgênero', mood:'Clima', key:'Tonalidade', duration:'Duração', title:'Título', lyrics:'Letra / Modo vocal', generate:'Gerar faixa', language:'Idioma', account:'Conta', logout:'Sair', welcome:'Bem-vindo ao Sonara', password:'Senha', signIn:'Entrar', createAccount:'Criar conta', register:'Registrar', forgotPassword:'Esqueceu a senha?', continueGoogle:'Continuar com Google', or:'ou', guest:'Continuar como convidado', seconds:'segundos', minutes:'minutos' },
  'pt-BR': { overview:'Visão geral', generator:'Gerador', production:'Produção', publishing:'Publicação', discovery:'Descoberta', analytics:'Análises', assistant:'Assistente IA', collaboration:'Colaboração', settings:'Configurações', generateMusic:'Gerar música', genreFamily:'Família musical', genre:'Gênero', subgenre:'Subgênero', mood:'Clima', key:'Tonalidade', duration:'Duração', title:'Título', lyrics:'Letra / Modo vocal', generate:'Gerar faixa', language:'Idioma', account:'Conta', logout:'Sair', welcome:'Bem-vindo ao Sonara', password:'Senha', signIn:'Entrar', createAccount:'Criar conta', register:'Cadastrar', forgotPassword:'Esqueceu a senha?', continueGoogle:'Continuar com Google', or:'ou', guest:'Continuar como convidado', seconds:'segundos', minutes:'minutos' },
  nl: { overview:'Overzicht', generator:'Generator', production:'Productie', publishing:'Publicatie', discovery:'Ontdekken', analytics:'Analyses', assistant:'AI-assistent', collaboration:'Samenwerking', settings:'Instellingen', generateMusic:'Muziek genereren', genre:'Genre', subgenre:'Subgenre', mood:'Sfeer', key:'Toonsoort', duration:'Duur', title:'Titel', language:'Taal', account:'Account', logout:'Afmelden', welcome:'Welkom bij Sonara', password:'Wachtwoord', signIn:'Aanmelden', createAccount:'Account maken', continueGoogle:'Doorgaan met Google', guest:'Doorgaan als gast' },
  pl: { overview:'Przegląd', generator:'Generator', production:'Produkcja', publishing:'Publikacja', discovery:'Odkrywanie', analytics:'Analityka', assistant:'Asystent AI', collaboration:'Współpraca', settings:'Ustawienia', generateMusic:'Generuj muzykę', genre:'Gatunek', subgenre:'Podgatunek', mood:'Nastrój', key:'Tonacja', duration:'Czas trwania', title:'Tytuł', language:'Język', account:'Konto', logout:'Wyloguj', welcome:'Witamy w Sonara', password:'Hasło', signIn:'Zaloguj', createAccount:'Utwórz konto', continueGoogle:'Kontynuuj z Google', guest:'Kontynuuj jako gość' },
  ro: { overview:'Prezentare', generator:'Generator', production:'Producție', publishing:'Publicare', discovery:'Descoperire', analytics:'Analiză', assistant:'Asistent AI', collaboration:'Colaborare', settings:'Setări', generateMusic:'Generează muzică', genre:'Gen', subgenre:'Subgen', mood:'Stare', key:'Tonalitate', duration:'Durată', language:'Limbă', welcome:'Bun venit la Sonara', signIn:'Autentificare', password:'Parolă', continueGoogle:'Continuă cu Google', guest:'Continuă ca oaspete' },
  cs: { overview:'Přehled', generator:'Generátor', production:'Produkce', publishing:'Publikování', discovery:'Objevování', analytics:'Analytika', assistant:'AI asistent', settings:'Nastavení', generateMusic:'Generovat hudbu', genre:'Žánr', subgenre:'Podžánr', mood:'Nálada', key:'Tónina', duration:'Délka', language:'Jazyk', welcome:'Vítejte v Sonara', signIn:'Přihlásit se', password:'Heslo', continueGoogle:'Pokračovat s Google', guest:'Pokračovat jako host' },
  hu: { overview:'Áttekintés', generator:'Generátor', production:'Produkció', publishing:'Kiadás', discovery:'Felfedezés', analytics:'Elemzés', assistant:'AI asszisztens', settings:'Beállítások', generateMusic:'Zene generálása', genre:'Műfaj', subgenre:'Alműfaj', mood:'Hangulat', key:'Hangnem', duration:'Időtartam', language:'Nyelv', welcome:'Üdv a Sonarában', signIn:'Bejelentkezés', password:'Jelszó', continueGoogle:'Folytatás Google-lel', guest:'Folytatás vendégként' },
  sv: { overview:'Översikt', generator:'Generator', production:'Produktion', publishing:'Publicering', discovery:'Upptäck', analytics:'Analys', assistant:'AI-assistent', settings:'Inställningar', generateMusic:'Generera musik', genre:'Genre', subgenre:'Subgenre', mood:'Stämning', key:'Tonart', duration:'Längd', language:'Språk', welcome:'Välkommen till Sonara', signIn:'Logga in', password:'Lösenord', continueGoogle:'Fortsätt med Google', guest:'Fortsätt som gäst' },
  fi: { overview:'Yleiskatsaus', generator:'Generaattori', production:'Tuotanto', publishing:'Julkaisu', discovery:'Löydä', analytics:'Analytiikka', assistant:'AI-avustaja', settings:'Asetukset', generateMusic:'Luo musiikkia', genre:'Genre', subgenre:'Alagenre', mood:'Tunnelma', key:'Sävellaji', duration:'Kesto', language:'Kieli', welcome:'Tervetuloa Sonaraan', signIn:'Kirjaudu', password:'Salasana', continueGoogle:'Jatka Googlella', guest:'Jatka vieraana' },
  da: { overview:'Oversigt', generator:'Generator', production:'Produktion', publishing:'Udgivelse', discovery:'Opdag', analytics:'Analyse', assistant:'AI-assistent', settings:'Indstillinger', generateMusic:'Generer musik', genre:'Genre', subgenre:'Undergenre', mood:'Stemning', key:'Toneart', duration:'Varighed', language:'Sprog', welcome:'Velkommen til Sonara', signIn:'Log ind', password:'Adgangskode', continueGoogle:'Fortsæt med Google', guest:'Fortsæt som gæst' },
  no: { overview:'Oversikt', generator:'Generator', production:'Produksjon', publishing:'Publisering', discovery:'Oppdag', analytics:'Analyse', assistant:'AI-assistent', settings:'Innstillinger', generateMusic:'Generer musikk', genre:'Sjanger', subgenre:'Undersjanger', mood:'Stemning', key:'Toneart', duration:'Varighet', language:'Språk', welcome:'Velkommen til Sonara', signIn:'Logg inn', password:'Passord', continueGoogle:'Fortsett med Google', guest:'Fortsett som gjest' },
  ru: { overview:'Обзор', generator:'Генератор', production:'Продакшн', publishing:'Публикация', discovery:'Открытия', analytics:'Аналитика', assistant:'ИИ-ассистент', collaboration:'Совместная работа', settings:'Настройки', generateMusic:'Создать музыку', genreFamily:'Музыкальная семья', genre:'Жанр', subgenre:'Поджанр', mood:'Настроение', key:'Тональность', duration:'Длительность', title:'Название', lyrics:'Текст / Вокал', generate:'Создать трек', language:'Язык', account:'Аккаунт', logout:'Выйти', welcome:'Добро пожаловать в Sonara', password:'Пароль', signIn:'Войти', createAccount:'Создать аккаунт', continueGoogle:'Продолжить с Google', guest:'Продолжить как гость', seconds:'секунд', minutes:'минут' },
  uk: { overview:'Огляд', generator:'Генератор', production:'Продакшн', publishing:'Публікація', discovery:'Відкриття', analytics:'Аналітика', assistant:'AI-асистент', settings:'Налаштування', generateMusic:'Створити музику', genre:'Жанр', subgenre:'Піджанр', mood:'Настрій', key:'Тональність', duration:'Тривалість', language:'Мова', welcome:'Ласкаво просимо до Sonara', signIn:'Увійти', password:'Пароль', continueGoogle:'Продовжити з Google', guest:'Продовжити як гість' },
  tr: { overview:'Genel Bakış', generator:'Üretici', production:'Prodüksiyon', publishing:'Yayınlama', discovery:'Keşfet', analytics:'Analitik', assistant:'AI Asistanı', settings:'Ayarlar', generateMusic:'Müzik üret', genre:'Tür', subgenre:'Alt tür', mood:'Ruh hali', key:'Ton', duration:'Süre', language:'Dil', account:'Hesap', logout:'Çıkış', welcome:'Sonara’ya hoş geldiniz', password:'Şifre', signIn:'Giriş yap', createAccount:'Hesap oluştur', continueGoogle:'Google ile devam et', guest:'Misafir olarak devam et' },
  el: { overview:'Επισκόπηση', generator:'Γεννήτρια', production:'Παραγωγή', publishing:'Δημοσίευση', discovery:'Ανακάλυψη', analytics:'Αναλύσεις', assistant:'Βοηθός AI', settings:'Ρυθμίσεις', generateMusic:'Δημιουργία μουσικής', genre:'Είδος', subgenre:'Υποείδος', mood:'Διάθεση', key:'Τονικότητα', duration:'Διάρκεια', language:'Γλώσσα', welcome:'Καλώς ήρθατε στο Sonara', signIn:'Σύνδεση', password:'Κωδικός', continueGoogle:'Συνέχεια με Google', guest:'Συνέχεια ως επισκέπτης' },
  ar: { overview:'نظرة عامة', generator:'المولّد', production:'الإنتاج', publishing:'النشر', discovery:'اكتشاف', analytics:'التحليلات', assistant:'مساعد الذكاء الاصطناعي', collaboration:'التعاون', settings:'الإعدادات', generateMusic:'إنشاء موسيقى', genreFamily:'عائلة موسيقية', genre:'النوع', subgenre:'النوع الفرعي', mood:'المزاج', key:'المقام', duration:'المدة', title:'العنوان', lyrics:'الكلمات / وضع الصوت', generate:'إنشاء المقطع', language:'اللغة', account:'الحساب', logout:'تسجيل الخروج', welcome:'مرحبًا بك في Sonara', password:'كلمة المرور', signIn:'تسجيل الدخول', createAccount:'إنشاء حساب', continueGoogle:'المتابعة باستخدام Google', guest:'المتابعة كضيف' },
  he: { overview:'סקירה', generator:'מחולל', production:'הפקה', publishing:'פרסום', discovery:'גילוי', analytics:'אנליטיקה', assistant:'עוזר AI', settings:'הגדרות', generateMusic:'יצירת מוזיקה', genre:'ז׳אנר', subgenre:'תת-ז׳אנר', mood:'אווירה', key:'סולם', duration:'משך', language:'שפה', welcome:'ברוכים הבאים ל-Sonara', signIn:'כניסה', password:'סיסמה', continueGoogle:'המשך עם Google', guest:'המשך כאורח' },
  hi: { overview:'अवलोकन', generator:'जनरेटर', production:'प्रोडक्शन', publishing:'प्रकाशन', discovery:'खोज', analytics:'विश्लेषण', assistant:'AI सहायक', settings:'सेटिंग्स', generateMusic:'संगीत बनाएँ', genre:'शैली', subgenre:'उपशैली', mood:'मूड', key:'की', duration:'अवधि', language:'भाषा', welcome:'Sonara में आपका स्वागत है', signIn:'साइन इन', password:'पासवर्ड', continueGoogle:'Google से जारी रखें', guest:'अतिथि के रूप में जारी रखें' },
  bn: { overview:'সারসংক্ষেপ', generator:'জেনারেটর', production:'প্রোডাকশন', publishing:'প্রকাশনা', discovery:'অনুসন্ধান', analytics:'বিশ্লেষণ', assistant:'AI সহকারী', settings:'সেটিংস', generateMusic:'সঙ্গীত তৈরি করুন', genre:'ধরন', subgenre:'উপধরন', mood:'মুড', duration:'সময়কাল', language:'ভাষা', welcome:'Sonara-তে স্বাগতম', signIn:'সাইন ইন', password:'পাসওয়ার্ড', continueGoogle:'Google দিয়ে চালিয়ে যান', guest:'অতিথি হিসেবে চালিয়ে যান' },
  th: { overview:'ภาพรวม', generator:'ตัวสร้าง', production:'โปรดักชัน', publishing:'เผยแพร่', discovery:'ค้นพบ', analytics:'การวิเคราะห์', assistant:'ผู้ช่วย AI', settings:'การตั้งค่า', generateMusic:'สร้างเพลง', genre:'แนวเพลง', subgenre:'แนวย่อย', mood:'อารมณ์', key:'คีย์', duration:'ระยะเวลา', language:'ภาษา', welcome:'ยินดีต้อนรับสู่ Sonara', signIn:'เข้าสู่ระบบ', password:'รหัสผ่าน', continueGoogle:'ดำเนินการต่อด้วย Google', guest:'ดำเนินการต่อในฐานะแขก' },
  vi: { overview:'Tổng quan', generator:'Trình tạo', production:'Sản xuất', publishing:'Phát hành', discovery:'Khám phá', analytics:'Phân tích', assistant:'Trợ lý AI', settings:'Cài đặt', generateMusic:'Tạo nhạc', genre:'Thể loại', subgenre:'Thể loại phụ', mood:'Tâm trạng', key:'Tông', duration:'Thời lượng', language:'Ngôn ngữ', welcome:'Chào mừng đến Sonara', signIn:'Đăng nhập', password:'Mật khẩu', continueGoogle:'Tiếp tục với Google', guest:'Tiếp tục với tư cách khách' },
  id: { overview:'Ikhtisar', generator:'Generator', production:'Produksi', publishing:'Publikasi', discovery:'Jelajahi', analytics:'Analitik', assistant:'Asisten AI', settings:'Pengaturan', generateMusic:'Buat musik', genre:'Genre', subgenre:'Subgenre', mood:'Suasana', key:'Kunci', duration:'Durasi', language:'Bahasa', welcome:'Selamat datang di Sonara', signIn:'Masuk', password:'Kata sandi', continueGoogle:'Lanjutkan dengan Google', guest:'Lanjutkan sebagai tamu' },
  ms: { overview:'Gambaran', generator:'Penjana', production:'Produksi', publishing:'Penerbitan', discovery:'Teroka', analytics:'Analitik', assistant:'Pembantu AI', settings:'Tetapan', generateMusic:'Jana muzik', genre:'Genre', subgenre:'Subgenre', mood:'Mood', duration:'Tempoh', language:'Bahasa', welcome:'Selamat datang ke Sonara', signIn:'Log masuk', password:'Kata laluan', continueGoogle:'Teruskan dengan Google', guest:'Teruskan sebagai tetamu' },
  fil: { overview:'Pangkalahatan', generator:'Generator', production:'Produksyon', publishing:'Paglalathala', discovery:'Tuklasin', analytics:'Analytics', assistant:'AI Assistant', settings:'Mga Setting', generateMusic:'Gumawa ng musika', genre:'Genre', subgenre:'Subgenre', mood:'Mood', duration:'Tagal', language:'Wika', welcome:'Maligayang pagdating sa Sonara', signIn:'Mag-sign in', password:'Password', continueGoogle:'Magpatuloy sa Google', guest:'Magpatuloy bilang bisita' },
  ja: { overview:'概要', generator:'ジェネレーター', production:'プロダクション', publishing:'配信', discovery:'ディスカバリー', analytics:'分析', assistant:'AIアシスタント', collaboration:'コラボレーション', settings:'設定', generateMusic:'音楽を生成', genreFamily:'音楽ファミリー', genre:'ジャンル', subgenre:'サブジャンル', mood:'ムード', key:'キー', duration:'長さ', title:'タイトル', lyrics:'歌詞 / ボーカルモード', generate:'トラックを生成', language:'言語', account:'アカウント', logout:'ログアウト', welcome:'Sonaraへようこそ', password:'パスワード', signIn:'ログイン', createAccount:'アカウント作成', continueGoogle:'Googleで続行', guest:'ゲストとして続行', seconds:'秒', minutes:'分' },
  ko: { overview:'개요', generator:'생성기', production:'프로덕션', publishing:'배포', discovery:'디스커버리', analytics:'분석', assistant:'AI 어시스턴트', settings:'설정', generateMusic:'음악 생성', genre:'장르', subgenre:'하위 장르', mood:'무드', key:'키', duration:'길이', title:'제목', language:'언어', account:'계정', logout:'로그아웃', welcome:'Sonara에 오신 것을 환영합니다', password:'비밀번호', signIn:'로그인', createAccount:'계정 만들기', continueGoogle:'Google로 계속', guest:'게스트로 계속' },
  'zh-CN': { overview:'概览', generator:'生成器', production:'制作', publishing:'发行', discovery:'发现', analytics:'分析', assistant:'AI 助手', collaboration:'协作', settings:'设置', generateMusic:'生成音乐', genreFamily:'音乐类别', genre:'流派', subgenre:'子流派', mood:'情绪', key:'调性', duration:'时长', title:'标题', lyrics:'歌词 / 人声模式', generate:'生成曲目', language:'语言', account:'账户', logout:'退出', welcome:'欢迎来到 Sonara', password:'密码', signIn:'登录', createAccount:'创建账户', continueGoogle:'使用 Google 继续', guest:'以访客身份继续', seconds:'秒', minutes:'分钟' },
  'zh-TW': { overview:'總覽', generator:'生成器', production:'製作', publishing:'發行', discovery:'探索', analytics:'分析', assistant:'AI 助手', collaboration:'協作', settings:'設定', generateMusic:'生成音樂', genreFamily:'音樂類別', genre:'曲風', subgenre:'子曲風', mood:'情緒', key:'調性', duration:'時長', title:'標題', lyrics:'歌詞 / 人聲模式', generate:'生成曲目', language:'語言', account:'帳戶', logout:'登出', welcome:'歡迎來到 Sonara', password:'密碼', signIn:'登入', createAccount:'建立帳戶', continueGoogle:'使用 Google 繼續', guest:'以訪客身分繼續', seconds:'秒', minutes:'分鐘' }
};

const aliases: Partial<Record<LanguageCode, LanguageCode>> = {
  'fr-CA':'fr', 'es-419':'es', 'pt-BR':'pt'
};

export function uiText(language: LanguageCode, key: keyof typeof en): string {
  const pack = packs[language] || packs[aliases[language] as LanguageCode] || {};
  return pack[key] || en[key];
}

export const UI_ENGLISH = en;
