import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Activity,
  Cable,
  CheckCircle2,
  CircleAlert,
  Cpu,
  Disc3,
  Gauge,
  Headphones,
  Link2,
  Loader2,
  Music2,
  Radio,
  RefreshCw,
  Settings2,
  SlidersHorizontal,
  Usb,
  Zap
} from 'lucide-react';

type Transport = 'midi' | 'hid' | 'bridge';
type Brand = 'Native Instruments' | 'AlphaTheta / Pioneer DJ' | 'Denon DJ' | 'Hercules' | 'Reloop' | 'Numark' | 'Allen & Heath' | 'RANE' | 'Roland' | 'Generic';
type DJDevice = { id: string; name: string; manufacturer: string; brand: Brand; transport: Transport; state: 'connected' | 'disconnected'; input?: any; output?: any; raw?: any };
type MidiLearnAction = 'deckA.play' | 'deckA.cue' | 'deckA.sync' | 'deckA.pitch' | 'deckA.volume' | 'deckB.play' | 'deckB.cue' | 'deckB.sync' | 'deckB.pitch' | 'deckB.volume' | 'mixer.crossfader' | 'mixer.filter';
type Mapping = Record<string, { status: number; data1: number; channel: number }>;
type DeckState = { playing: boolean; cue: boolean; sync: boolean; pitch: number; volume: number };

const DEVICE_KEY = 'sonara.dj.mapping.v1';
const BRIDGE_URL = 'ws://127.0.0.1:49686';
const BRAND_CARDS: Array<{ brand: Brand; detail: string; protocols: string[] }> = [
  { brand: 'Native Instruments', detail: 'Traktor Kontrol e controller Traktor Ready', protocols: ['MIDI', 'HID/NHL via Bridge', 'Traktor Mapping'] },
  { brand: 'AlphaTheta / Pioneer DJ', detail: 'CDJ, XDJ, DDJ, DJM e controller compatibili', protocols: ['MIDI', 'HID', 'PRO DJ LINK via Bridge'] },
  { brand: 'Denon DJ', detail: 'Prime, SC, LC, MC e Engine DJ hardware', protocols: ['MIDI', 'HID', 'Ableton Link / Network via Bridge'] },
  { brand: 'Hercules', detail: 'DJControl e controller MIDI class-compliant', protocols: ['MIDI', 'Mapping SONARA'] },
  { brand: 'Reloop', detail: 'Mixon, Ready, Buddy e controller MIDI/HID', protocols: ['MIDI', 'HID via Bridge'] },
  { brand: 'Numark', detail: 'Mixtrack, NS e controller compatibili', protocols: ['MIDI', 'Audio via Bridge'] },
  { brand: 'Allen & Heath', detail: 'Xone e mixer/controller compatibili', protocols: ['MIDI', 'Audio / Network via Bridge'] },
  { brand: 'RANE', detail: 'Performer, Four, One, Twelve e mixer', protocols: ['MIDI', 'HID / Audio via Bridge'] },
  { brand: 'Roland', detail: 'DJ series e controller USB MIDI', protocols: ['MIDI', 'Audio via Bridge'] },
  { brand: 'Generic', detail: 'Qualsiasi controller che espone porte MIDI standard', protocols: ['Generic MIDI', 'MIDI Learn'] }
];
const LEARN_ACTIONS: Array<{ id: MidiLearnAction; label: string }> = [
  { id: 'deckA.play', label: 'Deck A · Play/Pause' }, { id: 'deckA.cue', label: 'Deck A · Cue' }, { id: 'deckA.sync', label: 'Deck A · Sync' }, { id: 'deckA.pitch', label: 'Deck A · Pitch' }, { id: 'deckA.volume', label: 'Deck A · Volume' },
  { id: 'deckB.play', label: 'Deck B · Play/Pause' }, { id: 'deckB.cue', label: 'Deck B · Cue' }, { id: 'deckB.sync', label: 'Deck B · Sync' }, { id: 'deckB.pitch', label: 'Deck B · Pitch' }, { id: 'deckB.volume', label: 'Deck B · Volume' },
  { id: 'mixer.crossfader', label: 'Mixer · Crossfader' }, { id: 'mixer.filter', label: 'Mixer · Filter' }
];
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

function detectBrand(name = '', manufacturer = ''): Brand {
  const value = `${name} ${manufacturer}`.toLowerCase();
  if (/native instruments|traktor|kontrol/.test(value)) return 'Native Instruments';
  if (/alphatheta|pioneer|ddj|cdj|xdj|djm/.test(value)) return 'AlphaTheta / Pioneer DJ';
  if (/denon|engine dj|prime|sc[0-9]|lc6000|mcx/.test(value)) return 'Denon DJ';
  if (/hercules|djcontrol/.test(value)) return 'Hercules';
  if (/reloop/.test(value)) return 'Reloop';
  if (/numark/.test(value)) return 'Numark';
  if (/allen.*heath|xone/.test(value)) return 'Allen & Heath';
  if (/rane/.test(value)) return 'RANE';
  if (/roland/.test(value)) return 'Roland';
  return 'Generic';
}
function readMapping(): Mapping { try { return JSON.parse(localStorage.getItem(DEVICE_KEY) || '{}') as Mapping; } catch { return {}; } }
function Capability({ label, active, detail }: { label: string; active: boolean; detail: string }) { return <div className={`rounded-xl border p-3 ${active ? 'border-emerald-500/20 bg-emerald-500/5' : 'border-slate-800 bg-slate-950/70'}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black text-white">{label}</span>{active ? <CheckCircle2 className="h-3.5 w-3.5 text-emerald-300" /> : <CircleAlert className="h-3.5 w-3.5 text-slate-600" />}</div><div className="mt-1 text-[9px] leading-4 text-slate-500">{detail}</div></div>; }
function Deck({ name, state, onChange }: { name: string; state: DeckState; onChange: (next: Partial<DeckState>) => void }) { return <div className="rounded-2xl border border-slate-800 bg-[#080b12] p-4"><div className="flex items-center justify-between"><div><div className="text-[9px] font-black uppercase tracking-[0.2em] text-purple-300">{name}</div><div className="mt-1 text-xs font-black text-white">Controller Monitor</div></div><Disc3 className={`h-7 w-7 text-slate-600 ${state.playing ? 'animate-spin' : ''}`} /></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={() => onChange({ playing: !state.playing })} className={`rounded-xl px-3 py-3 text-[10px] font-black ${state.playing ? 'bg-emerald-500 text-black' : 'border border-slate-800 bg-slate-950 text-slate-300'}`}>PLAY</button><button onClick={() => onChange({ cue: !state.cue })} className={`rounded-xl px-3 py-3 text-[10px] font-black ${state.cue ? 'bg-amber-400 text-black' : 'border border-slate-800 bg-slate-950 text-slate-300'}`}>CUE</button><button onClick={() => onChange({ sync: !state.sync })} className={`rounded-xl px-3 py-3 text-[10px] font-black ${state.sync ? 'bg-cyan-400 text-black' : 'border border-slate-800 bg-slate-950 text-slate-300'}`}>SYNC</button></div><label className="mt-4 block text-[9px] font-bold text-slate-500">PITCH <span className="float-right text-white">{state.pitch > 0 ? '+' : ''}{state.pitch.toFixed(1)}%</span><input type="range" min={-16} max={16} step={0.1} value={state.pitch} onChange={event => onChange({ pitch: Number(event.target.value) })} className="mt-2 w-full accent-purple-500" /></label><label className="mt-3 block text-[9px] font-bold text-slate-500">VOLUME <span className="float-right text-white">{Math.round(state.volume * 100)}%</span><input type="range" min={0} max={1} step={0.01} value={state.volume} onChange={event => onChange({ volume: Number(event.target.value) })} className="mt-2 w-full accent-purple-500" /></label></div>; }

export default function DJConnectHub() {
  const [devices, setDevices] = useState<DJDevice[]>([]); const [status, setStatus] = useState('Pronto per collegare una console DJ.'); const [busy, setBusy] = useState(false); const [bridgeState, setBridgeState] = useState<'offline'|'checking'|'online'>('offline'); const [eventLog, setEventLog] = useState<string[]>([]); const [learnAction, setLearnAction] = useState<MidiLearnAction|''>(''); const [mapping, setMapping] = useState<Mapping>(readMapping); const [deckA, setDeckA] = useState<DeckState>({ playing:false,cue:false,sync:false,pitch:0,volume:.82 }); const [deckB, setDeckB] = useState<DeckState>({ playing:false,cue:false,sync:false,pitch:0,volume:.82 }); const [crossfader,setCrossfader]=useState(0); const [filter,setFilter]=useState(0); const midiAccessRef=useRef<any>(null); const bridgeRef=useRef<WebSocket|null>(null);
  const browserCaps = useMemo(() => ({ midi: typeof (navigator as any).requestMIDIAccess === 'function', hid: Boolean((navigator as any).hid), usb: Boolean((navigator as any).usb), audioOutput: typeof (HTMLMediaElement.prototype as any).setSinkId === 'function' }), []);
  const log=(value:string)=>setEventLog(current=>[value,...current].slice(0,40));
  const applyMappedAction=(statusByte:number,data1:number,data2:number)=>{const channel=statusByte&0x0f;const command=statusByte&0xf0;const entries=Object.entries(mapping) as Array<[MidiLearnAction,Mapping[string]]>;const match=entries.find(([,rule])=>rule.data1===data1&&rule.channel===channel&&(rule.status&0xf0)===command);if(!match)return;const[action]=match;const pressed=data2>0;const normalized=clamp(data2/127,0,1);if(action==='deckA.play'&&pressed)setDeckA(c=>({...c,playing:!c.playing}));if(action==='deckA.cue')setDeckA(c=>({...c,cue:pressed}));if(action==='deckA.sync'&&pressed)setDeckA(c=>({...c,sync:!c.sync}));if(action==='deckA.pitch')setDeckA(c=>({...c,pitch:normalized*32-16}));if(action==='deckA.volume')setDeckA(c=>({...c,volume:normalized}));if(action==='deckB.play'&&pressed)setDeckB(c=>({...c,playing:!c.playing}));if(action==='deckB.cue')setDeckB(c=>({...c,cue:pressed}));if(action==='deckB.sync'&&pressed)setDeckB(c=>({...c,sync:!c.sync}));if(action==='deckB.pitch')setDeckB(c=>({...c,pitch:normalized*32-16}));if(action==='deckB.volume')setDeckB(c=>({...c,volume:normalized}));if(action==='mixer.crossfader')setCrossfader(normalized*2-1);if(action==='mixer.filter')setFilter(normalized*2-1);};
  const handleMidiMessage=(event:any)=>{const data=Array.from(event.data||[]) as number[];if(data.length<2)return;const[statusByte=0,data1=0,data2=0]=data;const channel=statusByte&0x0f;log(`MIDI · ch ${channel+1} · 0x${statusByte.toString(16)} · ${data1} · ${data2}`);if(learnAction){const next={...mapping,[learnAction]:{status:statusByte,data1,channel}};setMapping(next);localStorage.setItem(DEVICE_KEY,JSON.stringify(next));setStatus(`Mappato: ${LEARN_ACTIONS.find(i=>i.id===learnAction)?.label||learnAction}`);setLearnAction('');return;}applyMappedAction(statusByte,data1,data2);};
  const syncMidiDevices=(access:any)=>{const byId=new Map<string,DJDevice>();for(const input of Array.from(access.inputs?.values?.()||[]) as any[]){const id=`midi-${input.id}`;byId.set(id,{id,name:input.name||'MIDI Controller',manufacturer:input.manufacturer||'Unknown',brand:detectBrand(input.name,input.manufacturer),transport:'midi',state:input.state==='disconnected'?'disconnected':'connected',input});input.onmidimessage=handleMidiMessage;}for(const output of Array.from(access.outputs?.values?.()||[]) as any[]){const existing=Array.from(byId.values()).find(i=>i.name===output.name&&i.manufacturer===output.manufacturer);if(existing)existing.output=output;}setDevices(current=>[...current.filter(i=>i.transport!=='midi'),...Array.from(byId.values())]);};
  const connectMidi=async()=>{if(!browserCaps.midi||busy){setStatus('Web MIDI non disponibile: usa Chrome/Edge desktop oppure SONARA DJ Bridge.');return;}setBusy(true);try{const access=await(navigator as any).requestMIDIAccess({sysex:false});midiAccessRef.current=access;syncMidiDevices(access);access.onstatechange=()=>syncMidiDevices(access);setStatus('Console MIDI rilevate. Muovi un controllo per verificare il flusso dati.');log('Web MIDI access granted');}catch(error){setStatus(error instanceof Error?error.message:'Permesso MIDI non concesso.');}finally{setBusy(false);}};
  const connectHid=async()=>{const hid=(navigator as any).hid;if(!hid||busy){setStatus('WebHID non disponibile: per HID professionale usa SONARA DJ Bridge.');return;}setBusy(true);try{const selected=await hid.requestDevice({filters:[]});const next:DJDevice[]=[];for(const device of selected as any[]){if(!device.opened)await device.open();device.oninputreport=(event:any)=>{const bytes=Array.from(new Uint8Array(event.data?.buffer||new ArrayBuffer(0))).slice(0,16);log(`HID · ${device.productName||'device'} · report ${event.reportId} · ${bytes.join(' ')}`);};next.push({id:`hid-${device.vendorId}-${device.productId}-${device.productName||'device'}`,name:device.productName||'HID DJ Controller',manufacturer:`VID ${device.vendorId.toString(16).padStart(4,'0')}`,brand:detectBrand(device.productName,''),transport:'hid',state:'connected',raw:device});}setDevices(current=>[...current.filter(i=>i.transport!=='hid'),...next]);setStatus(next.length?`${next.length} dispositivo/i HID collegati.`:'Nessun dispositivo HID selezionato.');}catch(error){setStatus(error instanceof Error?error.message:'Connessione HID non riuscita.');}finally{setBusy(false);}};
  const checkBridge=()=>{if(bridgeState==='checking')return;setBridgeState('checking');bridgeRef.current?.close();try{const socket=new WebSocket(BRIDGE_URL);bridgeRef.current=socket;const timeout=window.setTimeout(()=>{if(socket.readyState!==WebSocket.OPEN)socket.close();setBridgeState(c=>c==='online'?c:'offline');},1300);socket.onopen=()=>{window.clearTimeout(timeout);setBridgeState('online');setDevices(current=>current.some(i=>i.id==='sonara-dj-bridge')?current:[...current,{id:'sonara-dj-bridge',name:'SONARA DJ Bridge',manufacturer:'SONARA',brand:'Generic',transport:'bridge',state:'connected'}]);setStatus('SONARA DJ Bridge rilevato: hardware professionale, network e driver possono essere gestiti localmente.');socket.send(JSON.stringify({type:'hello',client:'sonara-web',version:1}));};socket.onmessage=e=>log(`BRIDGE · ${String(e.data).slice(0,140)}`);socket.onerror=()=>undefined;socket.onclose=()=>setBridgeState('offline');}catch{setBridgeState('offline');}};
  useEffect(()=>{checkBridge();return()=>{if(midiAccessRef.current)midiAccessRef.current.onstatechange=null;bridgeRef.current?.close();};},[]);
  const resetMapping=()=>{setMapping({});localStorage.removeItem(DEVICE_KEY);setLearnAction('');setStatus('Mapping MIDI azzerato.');};

  return <div className="space-y-5 pb-10">
    <section className="overflow-hidden rounded-3xl border border-purple-500/20 bg-[radial-gradient(circle_at_top_right,rgba(109,40,217,.22),transparent_36%),linear-gradient(145deg,#070912,#05070c)] p-5 shadow-2xl sm:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-fuchsia-500/20 bg-fuchsia-500/10 px-2.5 py-1 text-[9px] font-black uppercase tracking-[0.2em] text-fuchsia-200">SONARA DJ CONNECT</span><span className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2.5 py-1 text-[9px] font-black text-emerald-300">UNIVERSAL HARDWARE HUB</span></div><h1 className="mt-4 text-2xl font-black tracking-tight text-white sm:text-3xl">Collega la tua console. SONARA riconosce il setup.</h1><p className="mt-3 max-w-2xl text-xs leading-6 text-slate-400">Controller MIDI, dispositivi HID e — tramite SONARA DJ Bridge — driver audio professionali, network DJ e protocolli specifici dei produttori. Nessuna console viene simulata: SONARA mostra solo connessioni realmente disponibili.</p></div><div className="grid min-w-[280px] grid-cols-2 gap-2"><button onClick={()=>void connectMidi()} disabled={busy} className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-fuchsia-600 to-purple-600 px-4 py-3 text-[10px] font-black text-white disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Music2 className="h-4 w-4"/>} MIDI</button><button onClick={()=>void connectHid()} disabled={busy} className="flex items-center justify-center gap-2 rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-4 py-3 text-[10px] font-black text-cyan-100 disabled:opacity-50"><Usb className="h-4 w-4"/> HID</button><button onClick={checkBridge} className="col-span-2 flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-[10px] font-black text-slate-200"><Cpu className="h-4 w-4"/> DJ BRIDGE · {bridgeState.toUpperCase()}</button></div></div><div className="mt-5 flex items-center gap-2 rounded-xl border border-slate-800 bg-black/20 px-3 py-2 text-[10px] text-slate-400"><Radio className="h-3.5 w-3.5 shrink-0 text-purple-300"/><span>{status}</span></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Capability label="Web MIDI" active={browserCaps.midi} detail="Knob, fader, pad, jog e pulsanti esposti come messaggi MIDI."/><Capability label="Web HID" active={browserCaps.hid} detail="Accesso HID con consenso utente per hardware compatibile."/><Capability label="Web USB" active={browserCaps.usb} detail="Rilevato nel browser; per hardware DJ complesso preferiamo il Bridge."/><Capability label="Audio Output" active={browserCaps.audioOutput} detail="Uscita browser dove disponibile; ASIO/CoreAudio multicanale passa dal Bridge."/></section>
    <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4 sm:p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-sm font-black text-white">Console collegate</h2><p className="mt-1 text-[10px] text-slate-500">Le porte vengono aggiornate quando colleghi o scolleghi un dispositivo.</p></div><button onClick={()=>void connectMidi()} className="rounded-lg border border-slate-800 bg-slate-950 p-2 text-slate-400"><RefreshCw className="h-4 w-4"/></button></div>{devices.length===0?<div className="flex min-h-40 flex-col items-center justify-center rounded-xl border border-dashed border-slate-800 bg-slate-950/50 p-5 text-center"><Cable className="h-7 w-7 text-slate-700"/><div className="mt-3 text-xs font-black text-slate-300">Nessuna console ancora collegata</div><div className="mt-1 max-w-sm text-[10px] leading-5 text-slate-600">Collega il controller via USB, accendilo e premi MIDI o HID. Per hardware standalone/network useremo SONARA DJ Bridge.</div></div>:<div className="space-y-2">{devices.map(device=><div key={device.id} className="flex flex-col justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/70 p-3 sm:flex-row sm:items-center"><div className="flex min-w-0 items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-purple-500/20 bg-purple-500/10 text-purple-300"><Disc3 className="h-4 w-4"/></div><div className="min-w-0"><div className="truncate text-xs font-black text-white">{device.name}</div><div className="mt-0.5 truncate text-[9px] text-slate-500">{device.brand} · {device.manufacturer}</div></div></div><div className="flex items-center gap-2"><span className="rounded-full border border-cyan-500/20 bg-cyan-500/10 px-2 py-1 text-[8px] font-black text-cyan-200">{device.transport.toUpperCase()}</span><span className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2 py-1 text-[8px] font-black text-emerald-300">CONNECTED</span></div></div>)}</div>}</div><div className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-black text-white">Live controller monitor</h2><p className="mt-1 text-[10px] text-slate-500">Verifica che SONARA riceva davvero dati dalla console.</p></div><Activity className="h-5 w-5 text-emerald-300"/></div><div className="mt-4 h-48 overflow-auto rounded-xl border border-slate-800 bg-[#03050a] p-3 font-mono text-[9px] leading-5 text-emerald-300/80">{eventLog.length?eventLog.map((item,index)=><div key={`${item}-${index}`}>{item}</div>):<span className="text-slate-700">In attesa di MIDI/HID input...</span>}</div></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4 sm:p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-sm font-black text-white">Universal MIDI Learn</h2><p className="mt-1 text-[10px] text-slate-500">Se il controller non ha ancora un profilo SONARA, associ i controlli senza scrivere codice.</p></div><button onClick={resetMapping} className="rounded-lg border border-slate-800 bg-slate-950 px-3 py-2 text-[9px] font-black text-slate-400">RESET MAPPING</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{LEARN_ACTIONS.map(action=>{const rule=mapping[action.id];const learning=learnAction===action.id;return <button key={action.id} onClick={()=>setLearnAction(learning?'':action.id)} className={`rounded-xl border p-3 text-left transition ${learning?'border-amber-400/50 bg-amber-400/10':rule?'border-emerald-500/25 bg-emerald-500/5':'border-slate-800 bg-slate-950'}`}><div className="text-[10px] font-black text-white">{action.label}</div><div className={`mt-1 text-[8px] font-bold ${learning?'text-amber-300':rule?'text-emerald-300':'text-slate-600'}`}>{learning?'MUOVI ORA IL CONTROLLO...':rule?`MIDI CH ${rule.channel+1} · ${rule.data1}`:'CLICCA PER LEARN'}</div></button>;})}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><Deck name="DECK A" state={deckA} onChange={patch=>setDeckA(c=>({...c,...patch}))}/><Deck name="DECK B" state={deckB} onChange={patch=>setDeckB(c=>({...c,...patch}))}/></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4 sm:p-5"><div className="flex items-center gap-3"><div className="rounded-xl border border-purple-500/20 bg-purple-500/10 p-2 text-purple-300"><SlidersHorizontal className="h-4 w-4"/></div><div><h2 className="text-sm font-black text-white">DJ Mixer Control Surface</h2><p className="mt-1 text-[10px] text-slate-500">Questi valori reagiscono anche ai controlli fisici associati con MIDI Learn.</p></div></div><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-[9px] font-bold text-slate-500">CROSSFADER <span className="float-right text-white">{crossfader<-.05?'A':crossfader>.05?'B':'CENTER'}</span><input type="range" min={-1} max={1} step={.01} value={crossfader} onChange={e=>setCrossfader(Number(e.target.value))} className="mt-2 w-full accent-fuchsia-500"/></label><label className="text-[9px] font-bold text-slate-500">MASTER FILTER <span className="float-right text-white">{Math.round(filter*100)}</span><input type="range" min={-1} max={1} step={.01} value={filter} onChange={e=>setFilter(Number(e.target.value))} className="mt-2 w-full accent-cyan-500"/></label></div></section>
    <section className="rounded-2xl border border-slate-800 bg-slate-900/55 p-4 sm:p-5"><div className="mb-4"><h2 className="text-sm font-black text-white">Hardware ecosystem</h2><p className="mt-1 text-[10px] text-slate-500">Architettura aperta: profili specifici per modello sopra un layer universale MIDI/HID/Bridge.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{BRAND_CARDS.map(item=><div key={item.brand} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3"><div className="flex items-center gap-2"><Headphones className="h-4 w-4 text-purple-300"/><span className="text-[10px] font-black text-white">{item.brand}</span></div><div className="mt-2 text-[9px] leading-4 text-slate-500">{item.detail}</div><div className="mt-3 flex flex-wrap gap-1">{item.protocols.map(p=><span key={p} className="rounded-md border border-slate-800 bg-slate-900 px-1.5 py-1 text-[7px] font-black text-slate-500">{p}</span>)}</div></div>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center gap-2 text-[10px] font-black text-white"><Link2 className="h-4 w-4 text-cyan-300"/> NETWORK SYNC</div><p className="mt-2 text-[9px] leading-5 text-slate-500">PRO DJ LINK, Engine DJ/Ableton Link e protocolli LAN vengono instradati dal DJ Bridge quando richiedono accesso locale o SDK specifici.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center gap-2 text-[10px] font-black text-white"><Gauge className="h-4 w-4 text-emerald-300"/> LOW LATENCY AUDIO</div><p className="mt-2 text-[9px] leading-5 text-slate-500">ASIO, CoreAudio e routing multicanale professionale non vengono finti nel browser: il Bridge espone solo endpoint realmente disponibili.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center gap-2 text-[10px] font-black text-white"><Settings2 className="h-4 w-4 text-fuchsia-300"/> DEVICE PROFILES</div><p className="mt-2 text-[9px] leading-5 text-slate-500">Ogni modello potrà avere mapping dedicato per jog, display, pad RGB, stems, hot cue, FX, loop, beatgrid e feedback LED.</p></div></section>
    <section className="rounded-2xl border border-purple-500/20 bg-purple-500/5 p-4 text-[10px] leading-5 text-purple-100"><div className="flex items-start gap-3"><Zap className="mt-0.5 h-4 w-4 shrink-0 text-fuchsia-300"/><div><b>Obiettivo SONARA DJ:</b> il DJ collega la console che già possiede, SONARA identifica il protocollo disponibile e carica il profilo corretto. Se il browser non può accedere direttamente all’hardware, il DJ Bridge locale mantiene la connessione a bassa latenza senza inventare compatibilità.</div></div></section>
  </div>;
}
